### ISSUE TITLE
pip install libzt returns a "Could not find a version that satisfies the requirement libzt (from versions: none)" error

### ISSUE THREAD

**Issue by Redstonamaniac21** [zerotier/libzt#181]
Every time I try and install it, it gives me that error. I am trying to install it in a virtual environment from windows powershell.

**Comment by tralph3** [comment]
libzt doesn't support Python 3.10 yet, it only supports Python3.5 to 3.9. You will need to use one of these versions in order to be able to install it.

**Comment by Redstonamaniac21** [comment]
Sorry for the late reply, when I use
`python -V`
It returns "Python 3.9.5" and it still won't install.

**Comment by tralph3** [comment]
Are you sure pip is using that same python version? You can try installing it in the form of `python -m pip install libzt` instead of calling pip directly, that way you ensure the python version you're using is the one you expect.

If it still fails, then I don't really know. I could install it, but I'm still having troubles importing it (#180) and I can't find a solution, which is halting a project of mine.

**Comment by joseph-henry** [comment]
I've been away from this repo for some time but I'll try to take a look at these python issues and update it soon.

**Comment by Redstonamaniac21** [comment]
I will try this on my other pc that has Linux on it when I get a chance and let you know.

**Comment by joseph-henry** [comment]
Looks like something in Python 3.10's import system broke the package. Nothing in the package structure changed so I'll need to find a workaround.

**Comment by tralph3** [comment]
Ok, I could install the Python 3.10 version, but when I try to import it it fails due to a circular import... apparently.

    Python 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import libzt
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/tralph3/.local/lib/python3.10/site-packages/libzt/__init__.py", line 1, in <module>
        from .libzt import *
      File "/home/tralph3/.local/lib/python3.10/site-packages/libzt/libzt.py", line 13, in <module>
        from . import _libzt
    ImportError: cannot import name '_libzt' from partially initialized module 'libzt' (most likely due to a circular import) (/home/tralph3/.local/lib/python3.10/site-packages/libzt/__init__.py)
    >>>

**Comment by tralph3** [comment]
No other version of libzt was installed.

**Comment by fregapple** [comment]
Hi! I am having a similar issue when using Pip.

![image](https://user-images.githubusercontent.com/82219216/184527469-c7c85fd7-ff04-4deb-b839-e2734e8b11d5.png)


I am using python 3.9.13 on Windows 11. Though trying on windows 10 has the same issue!

I see a lot of references to MacOS and linux. Does this not work with Windows?

**Comment by fregapple** [comment]
bump! Wondering if there has been any work on Windows versions for python 3.10 and above.
I halted my project and started something else while I wait as I'd like to use this rather than python's sockets

**Comment by fregapple** [comment]
@joseph-henry Has this project been abandoned for Windows?

**Comment by fregapple** [comment]
@joseph-henry 
Just checking up and seeing if you have a windows python wheel available.

Cheers

**Comment by fregapple** [comment]
@joseph-henry bump

**Comment by fregapple** [comment]
@joseph-henry saw a reddit post recently where you said you'd said you be looking into windows builds. Any luck?
