### ISSUE TITLE
Unable to Build on Ubuntu 20.04

### ISSUE THREAD

**Issue by paulrd** [zerotier/libzt#68]
I notice that the binary downloads are also missing the linux builds. I get the following error when I tried make host:
```
[ 47%] Linking CXX executable bin/server
/usr/bin/ld: lib/libzt.a(Controls.cpp.o): in function `zts_start':
Controls.cpp:(.text+0x2e3): undefined reference to `pthread_create'
/usr/bin/ld: Controls.cpp:(.text+0x2fb): undefined reference to `pthread_create'
/usr/bin/ld: Controls.cpp:(.text+0x312): undefined reference to `pthread_setname_np'
/usr/bin/ld: Controls.cpp:(.text+0x326): undefined reference to `pthread_setname_np'
/usr/bin/ld: Controls.cpp:(.text+0x391): undefined reference to `pthread_setname_np'
/usr/bin/ld: Controls.cpp:(.text+0x3a2): undefined reference to `pthread_setname_np'
/usr/bin/ld: lib/libzt.a(VirtualTap.cpp.o): in function `ZeroTier::_main_lwip_driver_loop(void*)':
VirtualTap.cpp:(.text+0x2c): undefined reference to `pthread_setname_np'
/usr/bin/ld: lib/libzt.a(VirtualTap.cpp.o): in function `ZeroTier::VirtualTap::~VirtualTap()':
VirtualTap.cpp:(.text+0x83a): undefined reference to `pthread_join'
/usr/bin/ld: lib/libzt.a(VirtualTap.cpp.o): in function `ZeroTier::VirtualTap::threadMain()':
VirtualTap.cpp:(.text+0xc3d): undefined reference to `pthread_setname_np'
/usr/bin/ld: lib/libzt.a(VirtualTap.cpp.o): in function `ZeroTier::VirtualTap::VirtualTap(char const*, ZeroTier::MAC const&, unsigned int, unsigned int, unsigned long, char const*, void (*)(void*, void*, unsigned long, ZeroTier::MAC const&, ZeroTier::MAC const&, unsigned int, unsigned int, void const*, unsigned int), void*)':
VirtualTap.cpp:(.text+0x19b7): undefined reference to `pthread_attr_setstacksize'
/usr/bin/ld: VirtualTap.cpp:(.text+0x19cc): undefined reference to `pthread_create'
/usr/bin/ld: lib/libzt.a(PortMapper.cpp.o): in function `ZeroTier::PortMapper::PortMapper(int, char const*)':
PortMapper.cpp:(.text+0xd5): undefined reference to `pthread_attr_setstacksize'
/usr/bin/ld: PortMapper.cpp:(.text+0xea): undefined reference to `pthread_create'
```

**Comment by paulrd** [comment]
I tried again using clang. I installed clang then used:
```make make_release CC=clang CXX=clang++```

**Comment by heri16** [comment]
`make clean; make update && make patch && make host_release CC=clang CXX=clang++`
